GearAdd = (vehicle player);
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
GearAdd addMagazine 'ItemComboLock';
