GearAdd = (vehicle player);
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
GearAdd addMagazine 'ItemSandbag';
