GearAdd = (vehicle player);
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
GearAdd addMagazine 'ItemTankTrap';
