GearAdd = (vehicle player);
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
GearAdd addMagazine 'ItemSandbagLarge';
