GearAdd = (vehicle player);
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
GearAdd addMagazine 'PartWoodPlywood';
