GearAdd = (vehicle player);
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
GearAdd addMagazine 'ItemCanvas';
