GearAdd = (vehicle player);
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
GearAdd addMagazine 'CinderBlocks';
