GearAdd = (vehicle player);
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
GearAdd addMagazine 'ItemBurlap';
