GearAdd = (vehicle player);
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
GearAdd addMagazine 'PartWoodPile';
