GearAdd = (vehicle player);
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
GearAdd addMagazine 'MortarBucket';
