GearAdd = (vehicle player);
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
GearAdd addMagazine 'PartWoodLumber';
