GearAdd = (vehicle player);
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
GearAdd addMagazine 'PartGeneric';
