GearAdd = (vehicle player);
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
GearAdd addMagazine 'ItemCorrugated';
