GearAdd = (vehicle player);
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
GearAdd addMagazine 'ItemWire';
