GearAdd = (vehicle player);
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
GearAdd addMagazine 'ItemLightBulb';
